/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg12411137_daniel_deras_proyecto1;

import java.awt.Dialog;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;
import javax.swing.JFrame;

/**
 *
 * @author danie
 */
public class Daniel_Deras_Proyecto1_1241 extends javax.swing.JFrame {

    /**
     * Creates new form Daniel_Deras_Proyecto1_12411137
     */
    public Daniel_Deras_Proyecto1_1241() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_goldlane = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_lesley = new javax.swing.JButton();
        label_fondo = new javax.swing.JLabel();
        panel_explane = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        btn_terizla = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label_fondo1 = new javax.swing.JLabel();
        panel_midlane = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        btn_cecilion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        label_fondo2 = new javax.swing.JLabel();
        panel_jungler = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        btn_yin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        label_fondo3 = new javax.swing.JLabel();
        panel_batalla_jungler = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        btn_farmear = new javax.swing.JButton();
        btn_tienda = new javax.swing.JButton();
        btn_ult = new javax.swing.JButton();
        btn_ataque = new javax.swing.JButton();
        btn_curar = new javax.swing.JButton();
        txt_vidaenemigo = new javax.swing.JLabel();
        txt_oro = new javax.swing.JLabel();
        txt_lvl = new javax.swing.JLabel();
        txt_vida = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        label_fondo4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_goldlane = new javax.swing.JButton();
        btn_midlane = new javax.swing.JButton();
        btn_jungler = new javax.swing.JButton();
        btn_explane = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lesley");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 150, 60));

        jButton1.setText("jButton1");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 230, 310));

        btn_lesley.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Imagen_lesley.jpg")); // NOI18N
        btn_lesley.setText("jButton1");
        btn_lesley.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lesleyMouseClicked(evt);
            }
        });
        btn_lesley.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lesleyActionPerformed(evt);
            }
        });
        jPanel2.add(btn_lesley, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 230, 240));

        label_fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Fondo_seleccion_heroe.png")); // NOI18N
        label_fondo.setText("jLabel1");
        jPanel2.add(label_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 390));

        javax.swing.GroupLayout panel_goldlaneLayout = new javax.swing.GroupLayout(panel_goldlane.getContentPane());
        panel_goldlane.getContentPane().setLayout(panel_goldlaneLayout);
        panel_goldlaneLayout.setHorizontalGroup(
            panel_goldlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_goldlaneLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_goldlaneLayout.setVerticalGroup(
            panel_goldlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_goldlaneLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_terizla.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\imagen_terizla.jpg")); // NOI18N
        btn_terizla.setText("jButton1");
        btn_terizla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_terizlaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_terizla, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 230, 240));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Terizla");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 230, 60));

        label_fondo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Fondo_seleccion_heroe.png")); // NOI18N
        label_fondo1.setText("Terizla");
        jPanel3.add(label_fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 390));

        javax.swing.GroupLayout panel_explaneLayout = new javax.swing.GroupLayout(panel_explane.getContentPane());
        panel_explane.getContentPane().setLayout(panel_explaneLayout);
        panel_explaneLayout.setHorizontalGroup(
            panel_explaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_explaneLayout.setVerticalGroup(
            panel_explaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cecilion.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Cecilion_mono.jpg")); // NOI18N
        btn_cecilion.setText("jButton1");
        btn_cecilion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cecilionMouseClicked(evt);
            }
        });
        btn_cecilion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cecilionActionPerformed(evt);
            }
        });
        jPanel4.add(btn_cecilion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 230, 240));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel2.setText("Cecilion");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 230, 60));

        label_fondo2.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Fondo_seleccion_heroe.png")); // NOI18N
        label_fondo2.setText("Terizla");
        jPanel4.add(label_fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 390));

        javax.swing.GroupLayout panel_midlaneLayout = new javax.swing.GroupLayout(panel_midlane.getContentPane());
        panel_midlane.getContentPane().setLayout(panel_midlaneLayout);
        panel_midlaneLayout.setHorizontalGroup(
            panel_midlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_midlaneLayout.setVerticalGroup(
            panel_midlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_yin.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Yin_mono.jpg")); // NOI18N
        btn_yin.setText("jButton1");
        btn_yin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_yinMouseClicked(evt);
            }
        });
        btn_yin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_yinActionPerformed(evt);
            }
        });
        jPanel5.add(btn_yin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 230, 240));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel4.setText("Yin");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 230, 60));

        label_fondo3.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Fondo_seleccion_heroe.png")); // NOI18N
        label_fondo3.setText("Terizla");
        jPanel5.add(label_fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 390));

        javax.swing.GroupLayout panel_junglerLayout = new javax.swing.GroupLayout(panel_jungler.getContentPane());
        panel_jungler.getContentPane().setLayout(panel_junglerLayout);
        panel_junglerLayout.setHorizontalGroup(
            panel_junglerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_junglerLayout.setVerticalGroup(
            panel_junglerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_farmear.setText("Farmear");
        btn_farmear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_farmearMouseClicked(evt);
            }
        });
        jPanel6.add(btn_farmear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        btn_tienda.setText("Tienda");
        jPanel6.add(btn_tienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        btn_ult.setText("Ultimate");
        jPanel6.add(btn_ult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        btn_ataque.setText("Atacar");
        btn_ataque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ataqueMouseClicked(evt);
            }
        });
        jPanel6.add(btn_ataque, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        btn_curar.setText("Curar");
        btn_curar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_curarMouseClicked(evt);
            }
        });
        jPanel6.add(btn_curar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 70, 20));

        txt_vidaenemigo.setText("Vida del Enemigo");
        jPanel6.add(txt_vidaenemigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        txt_oro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_oro.setForeground(new java.awt.Color(255, 255, 255));
        txt_oro.setText("Oro");
        jPanel6.add(txt_oro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 70, 20));

        txt_lvl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_lvl.setForeground(new java.awt.Color(255, 255, 255));
        txt_lvl.setText("Lvl");
        jPanel6.add(txt_lvl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, 20));

        txt_vida.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        txt_vida.setForeground(new java.awt.Color(255, 255, 255));
        txt_vida.setText("Vida");
        jPanel6.add(txt_vida, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 80, -1));

        jLabel5.setText("jLabel5");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 90, 130));

        label_fondo4.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\fondo de batalla(descarga).jpeg")); // NOI18N
        label_fondo4.setText("Terizla");
        jPanel6.add(label_fondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 650, 310));

        javax.swing.GroupLayout panel_batalla_junglerLayout = new javax.swing.GroupLayout(panel_batalla_jungler.getContentPane());
        panel_batalla_jungler.getContentPane().setLayout(panel_batalla_junglerLayout);
        panel_batalla_junglerLayout.setHorizontalGroup(
            panel_batalla_junglerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_batalla_junglerLayout.setVerticalGroup(
            panel_batalla_junglerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setName("Menu"); // NOI18N

        jPanel1.setName("Menu"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_goldlane.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\GoldLane(prueba).png")); // NOI18N
        btn_goldlane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_goldlaneMouseClicked(evt);
            }
        });
        jPanel1.add(btn_goldlane, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 50, 50));

        btn_midlane.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Mid_lane_imagen.png")); // NOI18N
        btn_midlane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_midlaneMouseClicked(evt);
            }
        });
        btn_midlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_midlaneActionPerformed(evt);
            }
        });
        jPanel1.add(btn_midlane, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 50, 50));

        btn_jungler.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Jungler_imagen.png")); // NOI18N
        btn_jungler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_junglerMouseClicked(evt);
            }
        });
        jPanel1.add(btn_jungler, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 50, 40));

        btn_explane.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Exp_lane_imagen.png")); // NOI18N
        btn_explane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_explaneMouseClicked(evt);
            }
        });
        jPanel1.add(btn_explane, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 50, 50));

        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Odio esto.jpg")); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("Menu");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_midlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_midlaneActionPerformed
        
    }//GEN-LAST:event_btn_midlaneActionPerformed

    private void btn_goldlaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_goldlaneMouseClicked
        //Genera una nueva ventana para que el usuario elija su personaje
        panel_goldlane.setVisible(true);
        panel_goldlane.setModal(true);
        panel_goldlane.pack();
        this.setVisible(false);
    }//GEN-LAST:event_btn_goldlaneMouseClicked

    private void btn_explaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_explaneMouseClicked
        //Genera una nueva ventana para que el usuario elija su personaje
        panel_explane.setVisible(true);
        panel_explane.setModal(true);
        panel_explane.pack();
        this.setVisible(false);
    }//GEN-LAST:event_btn_explaneMouseClicked

    private void btn_lesleyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lesleyActionPerformed
        
    }//GEN-LAST:event_btn_lesleyActionPerformed

    private void btn_terizlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_terizlaActionPerformed
        /*Al momento de presionar el boton de la seleccion de heroes nos abre una nueva ventana y crea el personaje
        y crea el enemigo y los almacena en un ArrayList separados*/
        Jugador jugador = new Jugador("Terizla", 1000, 0, 1, 20);
        jugadores.add(jugador);
    }//GEN-LAST:event_btn_terizlaActionPerformed

    private void btn_lesleyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lesleyMouseClicked
        /*Al momento de presionar el boton de la seleccion de heroes nos abre una nueva ventana y crea el personaje
        y crea el enemigo y los almacena en un ArrayList separados*/
        Jugador jugador = new Jugador("Lesley", 1000, 0, 1, 10);
        jugadores.add(jugador);
        
    }//GEN-LAST:event_btn_lesleyMouseClicked

    private void btn_midlaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_midlaneMouseClicked
        //Genera una nueva ventana para que el usuario elija su personaje
        panel_midlane.setVisible(true);
        panel_midlane.setModal(true);
        panel_midlane.pack();
        this.setVisible(false);
    }//GEN-LAST:event_btn_midlaneMouseClicked

    private void btn_junglerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_junglerMouseClicked
        //Genera una nueva ventana para que el usuario elija su personaje
        panel_jungler.setVisible(true);
        panel_jungler.setModal(true);
        panel_jungler.pack();
        this.setVisible(false);
    }//GEN-LAST:event_btn_junglerMouseClicked

    private void btn_cecilionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cecilionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cecilionActionPerformed

    private void btn_yinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_yinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_yinActionPerformed

    private void btn_cecilionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cecilionMouseClicked
        /*Al momento de presionar el boton de la seleccion de heroes nos abre una nueva ventana y crea el personaje
        y crea el enemigo y los almacena en un ArrayList separados*/
        Jugador jugador = new Jugador("Cecilion", 1000, 0, 1, 15);
        jugadores.add(jugador);
    }//GEN-LAST:event_btn_cecilionMouseClicked

    private void btn_yinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yinMouseClicked
        /*Al momento de presionar el boton de la seleccion de heroes nos abre una nueva ventana y crea el personaje
        y crea el enemigo y los almacena en un ArrayList separados*/
        Jugador jugador = new Jugador("Yin", 1000, 0, 1, 20);
        jugadores.add(jugador);
        Enemigo enemigo = new Enemigo("Alpha", 1000,0,1,15);
        enemigos.add(enemigo);
        jugadores.get(0).setVida(900);
        txt_vida.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
        txt_lvl.setText(String.valueOf("Lvl " + jugadores.get(0).getNivel()) + "/10");
        txt_oro.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
        txt_vidaenemigo.setText(String.valueOf(enemigos.get(0).getVida()) + "/1000");
        panel_batalla_jungler.setVisible(true);
        panel_batalla_jungler.setModal(true);
        panel_batalla_jungler.pack();
        panel_jungler.setVisible(false);
        
    }//GEN-LAST:event_btn_yinMouseClicked

    private void btn_curarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_curarMouseClicked
        //Aumenta la vida del jugador
        if (jugadores.get(0).getVida()<1000 && cont_vida > 0) {
            jugadores.get(0).setVida(jugadores.get(0).getVida() + 50);
            txt_vida.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
            cont_vida--;
        }
        if (cont_vida <= 0) {
            System.out.println("Se te acabaron las curas");
        }
        if (jugadores.get(0).getVida()>999) {
            System.out.println("Ya tienes vida completa");
            jugadores.get(0).setVida(1000);
            txt_vida.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
        }
        
        
    }//GEN-LAST:event_btn_curarMouseClicked

    private void btn_farmearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_farmearMouseClicked
        //Esta accion genera oro al jugador y al mismo tiempo genera un porcentaje de nivel
        jugadores.get(0).setOro(jugadores.get(0).getOro() + 250);
        txt_oro.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
        cont_oro ++;
        SubirLvl();
        txt_lvl.setText(String.valueOf("Lvl " + jugadores.get(0).getNivel()) + "/10");

    }//GEN-LAST:event_btn_farmearMouseClicked

    private void btn_ataqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ataqueMouseClicked

        enemigos.get(0).setVida(enemigos.get(0).getVida() - jugadores.get(0).getDano());
        txt_vidaenemigo.setText(String.valueOf(enemigos.get(0).getVida()) + "/1000");

    }//GEN-LAST:event_btn_ataqueMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daniel_Deras_Proyecto1_1241.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daniel_Deras_Proyecto1_1241.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daniel_Deras_Proyecto1_1241.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daniel_Deras_Proyecto1_1241.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daniel_Deras_Proyecto1_1241().setVisible(true);
            }
        });
    }
    //metodo de Inteligencia Artificial
    //Por cada turno que tenga el jugador tambien el bot va actuar dependiendo de un random
    public void Bot(){
        int random = numr.nextInt(10);
        //Atacar
        if (random == 1) {
            jugadores.get(0).setVida( jugadores.get(0).getVida() - enemigos.get(0).getDano());
        }//Farmear
        else if (random == 2) {
            enemigos.get(0).setOro(enemigos.get(0).getOro() + 250);
              
        }//Comprar
        else if (random == 3) {
            //Aqui tengo que poner la opcion de poder comprar objetos  
            //if oro es mayor que esto compro esto
        }
    
    }
    //Metodo para validar suber de nivel
    public void SubirLvl(){
        switch (cont_oro){
                case 2:
                    jugadores.get(0).setNivel(2);
                    break;
                case 4:
                    jugadores.get(0).setNivel(3);
                    break;
                case 6:
                    jugadores.get(0).setNivel(4);
                    break;
                case 8:
                    jugadores.get(0).setNivel(5);
                    break;
                case 10:
                    jugadores.get(0).setNivel(6);
                    break;
                case 12:
                    jugadores.get(0).setNivel(7);
                    break;
                case 14:
                    jugadores.get(0).setNivel(8);
                    break;
                case 16:
                    jugadores.get(0).setNivel(9);
                    break;
                case 18:
                    jugadores.get(0).setNivel(10);
                    break;
            }
    }
    

    //Variables globales
    ArrayList<Jugador> jugadores = new ArrayList();
    ArrayList<Enemigo> enemigos = new ArrayList();
    int cont_vida = 3;
    int cont_oro = 0;
    Random numr = new Random();
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ataque;
    private javax.swing.JButton btn_cecilion;
    private javax.swing.JButton btn_curar;
    private javax.swing.JButton btn_explane;
    private javax.swing.JButton btn_farmear;
    private javax.swing.JButton btn_goldlane;
    private javax.swing.JButton btn_jungler;
    private javax.swing.JButton btn_lesley;
    private javax.swing.JButton btn_midlane;
    private javax.swing.JButton btn_terizla;
    private javax.swing.JButton btn_tienda;
    private javax.swing.JButton btn_ult;
    private javax.swing.JButton btn_yin;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel label_fondo;
    private javax.swing.JLabel label_fondo1;
    private javax.swing.JLabel label_fondo2;
    private javax.swing.JLabel label_fondo3;
    private javax.swing.JLabel label_fondo4;
    private javax.swing.JDialog panel_batalla_jungler;
    private javax.swing.JDialog panel_explane;
    private javax.swing.JDialog panel_goldlane;
    private javax.swing.JDialog panel_jungler;
    private javax.swing.JDialog panel_midlane;
    private javax.swing.JLabel txt_lvl;
    private javax.swing.JLabel txt_oro;
    private javax.swing.JLabel txt_vida;
    private javax.swing.JLabel txt_vidaenemigo;
    // End of variables declaration//GEN-END:variables
}
