/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg12411137_daniel_deras_proyecto1;

import java.awt.Dialog;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class Daniel_Deras_Proyecto1_1241 extends javax.swing.JFrame {

    /**
     * Creates new form Daniel_Deras_Proyecto1_12411137
     */
    public Daniel_Deras_Proyecto1_1241() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_goldlane = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_lesley = new javax.swing.JButton();
        label_fondo = new javax.swing.JLabel();
        panel_explane = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        btn_terizla = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label_fondo1 = new javax.swing.JLabel();
        panel_midlane = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        btn_cecilion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        label_fondo2 = new javax.swing.JLabel();
        panel_jungler = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        btn_yin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        label_fondo3 = new javax.swing.JLabel();
        panel_batalla_jungler = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        btn_farmear = new javax.swing.JButton();
        btn_tienda = new javax.swing.JButton();
        btn_ult = new javax.swing.JButton();
        btn_ataque = new javax.swing.JButton();
        btn_curar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txt_vidaenemigo = new javax.swing.JLabel();
        txt_oro = new javax.swing.JLabel();
        txt_lvl = new javax.swing.JLabel();
        txt_vida = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        label_fondo4 = new javax.swing.JLabel();
        panel_tienda = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        btn_garrasdehaas = new javax.swing.JButton();
        btn_filodesesperante = new javax.swing.JButton();
        btn_varitadegenio = new javax.swing.JButton();
        btn_alassangrientas = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btn_regresar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        panel_batalla_mid = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        btn_farmear1 = new javax.swing.JButton();
        btn_tienda1 = new javax.swing.JButton();
        btn_ult1 = new javax.swing.JButton();
        btn_ataque1 = new javax.swing.JButton();
        btn_curar1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txt_vidaenemigo1 = new javax.swing.JLabel();
        txt_oro1 = new javax.swing.JLabel();
        txt_lvl1 = new javax.swing.JLabel();
        txt_vida1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_fondo5 = new javax.swing.JLabel();
        panel_batalla_exp = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        btn_farmear2 = new javax.swing.JButton();
        btn_tienda2 = new javax.swing.JButton();
        btn_ult2 = new javax.swing.JButton();
        btn_ataque2 = new javax.swing.JButton();
        btn_curar2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_vidaenemigo2 = new javax.swing.JLabel();
        txt_oro2 = new javax.swing.JLabel();
        txt_lvl2 = new javax.swing.JLabel();
        txt_vida2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        label_fondo6 = new javax.swing.JLabel();
        panel_batalla_gold = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        btn_farmear3 = new javax.swing.JButton();
        btn_tienda3 = new javax.swing.JButton();
        btn_ult3 = new javax.swing.JButton();
        btn_ataque3 = new javax.swing.JButton();
        btn_curar3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_vidaenemigo3 = new javax.swing.JLabel();
        txt_oro3 = new javax.swing.JLabel();
        txt_lvl3 = new javax.swing.JLabel();
        txt_vida3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        label_fondo7 = new javax.swing.JLabel();
        panel_nexo = new javax.swing.JDialog();
        jPanel11 = new javax.swing.JPanel();
        btn_ataquenexo = new javax.swing.JButton();
        txt_vidanexo = new javax.swing.JLabel();
        txt_vidajugador = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Victory = new javax.swing.JDialog();
        jPanel12 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        Defeat = new javax.swing.JDialog();
        jPanel13 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_goldlane = new javax.swing.JButton();
        btn_midlane = new javax.swing.JButton();
        btn_jungler = new javax.swing.JButton();
        btn_explane = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lesley");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 150, 60));

        btn_lesley.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Imagen_lesley.jpg")); // NOI18N
        btn_lesley.setText("jButton1");
        btn_lesley.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lesleyMouseClicked(evt);
            }
        });
        btn_lesley.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lesleyActionPerformed(evt);
            }
        });
        jPanel2.add(btn_lesley, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 230, 240));

        label_fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Fondo_seleccion_heroe.png")); // NOI18N
        label_fondo.setText("jLabel1");
        jPanel2.add(label_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 390));

        javax.swing.GroupLayout panel_goldlaneLayout = new javax.swing.GroupLayout(panel_goldlane.getContentPane());
        panel_goldlane.getContentPane().setLayout(panel_goldlaneLayout);
        panel_goldlaneLayout.setHorizontalGroup(
            panel_goldlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_goldlaneLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_goldlaneLayout.setVerticalGroup(
            panel_goldlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_goldlaneLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_terizla.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\imagen_terizla.jpg")); // NOI18N
        btn_terizla.setText("jButton1");
        btn_terizla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_terizlaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_terizla, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 230, 240));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Terizla");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 230, 60));

        label_fondo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Fondo_seleccion_heroe.png")); // NOI18N
        label_fondo1.setText("Terizla");
        jPanel3.add(label_fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 390));

        javax.swing.GroupLayout panel_explaneLayout = new javax.swing.GroupLayout(panel_explane.getContentPane());
        panel_explane.getContentPane().setLayout(panel_explaneLayout);
        panel_explaneLayout.setHorizontalGroup(
            panel_explaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_explaneLayout.setVerticalGroup(
            panel_explaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cecilion.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Cecilion_mono.jpg")); // NOI18N
        btn_cecilion.setText("jButton1");
        btn_cecilion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cecilionMouseClicked(evt);
            }
        });
        btn_cecilion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cecilionActionPerformed(evt);
            }
        });
        jPanel4.add(btn_cecilion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 230, 240));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel2.setText("Cecilion");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 230, 60));

        label_fondo2.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Fondo_seleccion_heroe.png")); // NOI18N
        label_fondo2.setText("Terizla");
        jPanel4.add(label_fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 390));

        javax.swing.GroupLayout panel_midlaneLayout = new javax.swing.GroupLayout(panel_midlane.getContentPane());
        panel_midlane.getContentPane().setLayout(panel_midlaneLayout);
        panel_midlaneLayout.setHorizontalGroup(
            panel_midlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_midlaneLayout.setVerticalGroup(
            panel_midlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_yin.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Yin_mono.jpg")); // NOI18N
        btn_yin.setText("jButton1");
        btn_yin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_yinMouseClicked(evt);
            }
        });
        btn_yin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_yinActionPerformed(evt);
            }
        });
        jPanel5.add(btn_yin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 230, 240));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel4.setText("Yin");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 230, 60));

        label_fondo3.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Fondo_seleccion_heroe.png")); // NOI18N
        label_fondo3.setText("Terizla");
        jPanel5.add(label_fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 390));

        javax.swing.GroupLayout panel_junglerLayout = new javax.swing.GroupLayout(panel_jungler.getContentPane());
        panel_jungler.getContentPane().setLayout(panel_junglerLayout);
        panel_junglerLayout.setHorizontalGroup(
            panel_junglerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_junglerLayout.setVerticalGroup(
            panel_junglerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_farmear.setText("Farmear");
        btn_farmear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_farmearMouseClicked(evt);
            }
        });
        jPanel6.add(btn_farmear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        btn_tienda.setText("Tienda");
        btn_tienda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tiendaMouseClicked(evt);
            }
        });
        jPanel6.add(btn_tienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        btn_ult.setText("Ultimate");
        btn_ult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ultMouseClicked(evt);
            }
        });
        jPanel6.add(btn_ult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        btn_ataque.setText("Atacar");
        btn_ataque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ataqueMouseClicked(evt);
            }
        });
        jPanel6.add(btn_ataque, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        btn_curar.setText("Curar");
        btn_curar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_curarMouseClicked(evt);
            }
        });
        jPanel6.add(btn_curar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 70, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\icono_alpha.png")); // NOI18N
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 90, 80));

        txt_vidaenemigo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_vidaenemigo.setText("Vida del Enemigo");
        jPanel6.add(txt_vidaenemigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        txt_oro.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_oro.setForeground(new java.awt.Color(255, 255, 255));
        txt_oro.setText("Oro");
        jPanel6.add(txt_oro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 120, 20));

        txt_lvl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_lvl.setForeground(new java.awt.Color(255, 255, 255));
        txt_lvl.setText("Lvl");
        jPanel6.add(txt_lvl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, 20));

        txt_vida.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_vida.setForeground(new java.awt.Color(255, 255, 255));
        txt_vida.setText("Vida");
        jPanel6.add(txt_vida, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 110, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\icono_yin.png")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 90, 70));

        label_fondo4.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\fondo de batalla(descarga).jpeg")); // NOI18N
        label_fondo4.setText("Terizla");
        jPanel6.add(label_fondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 650, 310));

        javax.swing.GroupLayout panel_batalla_junglerLayout = new javax.swing.GroupLayout(panel_batalla_jungler.getContentPane());
        panel_batalla_jungler.getContentPane().setLayout(panel_batalla_junglerLayout);
        panel_batalla_junglerLayout.setHorizontalGroup(
            panel_batalla_junglerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_batalla_junglerLayout.setVerticalGroup(
            panel_batalla_junglerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_garrasdehaas.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\garras_haas.png")); // NOI18N
        btn_garrasdehaas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_garrasdehaasMouseClicked(evt);
            }
        });
        jPanel7.add(btn_garrasdehaas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 60, 60));

        btn_filodesesperante.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\filo desesperante.png")); // NOI18N
        btn_filodesesperante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_filodesesperanteMouseClicked(evt);
            }
        });
        jPanel7.add(btn_filodesesperante, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 60, 60));

        btn_varitadegenio.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\VaritadeGenio.jpg")); // NOI18N
        btn_varitadegenio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_varitadegenioMouseClicked(evt);
            }
        });
        jPanel7.add(btn_varitadegenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 60, 60));

        btn_alassangrientas.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Alas_sangrientas.png")); // NOI18N
        btn_alassangrientas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_alassangrientasMouseClicked(evt);
            }
        });
        jPanel7.add(btn_alassangrientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 60, 60));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("+70 dano");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 90, -1));

        btn_regresar.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\regresar_.png")); // NOI18N
        btn_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regresarMouseClicked(evt);
            }
        });
        jPanel7.add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 60));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Alas sangrientas");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 90, -1));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("1810 Oro");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 90, -1));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("+100 dano");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 90, -1));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("3010 Oro");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 90, -1));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("+100 vida");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 90, -1));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("2000 Oro");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 90, -1));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("+200 vida");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 90, -1));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("3010 Oro");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 90, -1));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Garras de Haas");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 90, -1));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Filo desesperante");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 90, -1));

        jLabel30.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Bienvenido a la Tienda");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 190, 30));

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("+90 dano");
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 90, -1));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Varita de genio");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 90, -1));

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("+60 dano");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 90, -1));

        javax.swing.GroupLayout panel_tiendaLayout = new javax.swing.GroupLayout(panel_tienda.getContentPane());
        panel_tienda.getContentPane().setLayout(panel_tiendaLayout);
        panel_tiendaLayout.setHorizontalGroup(
            panel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        panel_tiendaLayout.setVerticalGroup(
            panel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_farmear1.setText("Farmear");
        btn_farmear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_farmear1MouseClicked(evt);
            }
        });
        jPanel8.add(btn_farmear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        btn_tienda1.setText("Tienda");
        btn_tienda1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tienda1MouseClicked(evt);
            }
        });
        jPanel8.add(btn_tienda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        btn_ult1.setText("Ultimate");
        btn_ult1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ult1MouseClicked(evt);
            }
        });
        jPanel8.add(btn_ult1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        btn_ataque1.setText("Atacar");
        btn_ataque1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ataque1MouseClicked(evt);
            }
        });
        jPanel8.add(btn_ataque1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        btn_curar1.setText("Curar");
        btn_curar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_curar1MouseClicked(evt);
            }
        });
        jPanel8.add(btn_curar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 70, 20));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\icono_zhask.png")); // NOI18N
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 80, 70));

        txt_vidaenemigo1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_vidaenemigo1.setText("Vida del Enemigo");
        jPanel8.add(txt_vidaenemigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        txt_oro1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_oro1.setForeground(new java.awt.Color(255, 255, 255));
        txt_oro1.setText("Oro");
        jPanel8.add(txt_oro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 120, 20));

        txt_lvl1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_lvl1.setForeground(new java.awt.Color(255, 255, 255));
        txt_lvl1.setText("Lvl");
        jPanel8.add(txt_lvl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, 20));

        txt_vida1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_vida1.setForeground(new java.awt.Color(255, 255, 255));
        txt_vida1.setText("Vida");
        jPanel8.add(txt_vida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 110, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\icono_cecilion.png")); // NOI18N
        jLabel6.setText("jLabel5");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 90, 60));

        label_fondo5.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\fondo de batalla(descarga).jpeg")); // NOI18N
        label_fondo5.setText("Terizla");
        jPanel8.add(label_fondo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 650, 310));

        javax.swing.GroupLayout panel_batalla_midLayout = new javax.swing.GroupLayout(panel_batalla_mid.getContentPane());
        panel_batalla_mid.getContentPane().setLayout(panel_batalla_midLayout);
        panel_batalla_midLayout.setHorizontalGroup(
            panel_batalla_midLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_batalla_midLayout.setVerticalGroup(
            panel_batalla_midLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_farmear2.setText("Farmear");
        btn_farmear2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_farmear2MouseClicked(evt);
            }
        });
        jPanel9.add(btn_farmear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        btn_tienda2.setText("Tienda");
        btn_tienda2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tienda2MouseClicked(evt);
            }
        });
        jPanel9.add(btn_tienda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        btn_ult2.setText("Ultimate");
        btn_ult2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ult2MouseClicked(evt);
            }
        });
        jPanel9.add(btn_ult2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        btn_ataque2.setText("Atacar");
        btn_ataque2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ataque2MouseClicked(evt);
            }
        });
        jPanel9.add(btn_ataque2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        btn_curar2.setText("Curar");
        btn_curar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_curar2MouseClicked(evt);
            }
        });
        jPanel9.add(btn_curar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 70, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\icono_yuzhong.png")); // NOI18N
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, 80));

        txt_vidaenemigo2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_vidaenemigo2.setText("Vida del Enemigo");
        jPanel9.add(txt_vidaenemigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        txt_oro2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_oro2.setForeground(new java.awt.Color(255, 255, 255));
        txt_oro2.setText("Oro");
        jPanel9.add(txt_oro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 120, 20));

        txt_lvl2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_lvl2.setForeground(new java.awt.Color(255, 255, 255));
        txt_lvl2.setText("Lvl");
        jPanel9.add(txt_lvl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, 20));

        txt_vida2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_vida2.setForeground(new java.awt.Color(255, 255, 255));
        txt_vida2.setText("Vida");
        jPanel9.add(txt_vida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 110, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\icono_terizla.png")); // NOI18N
        jLabel7.setText("jLabel5");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 90, 70));

        label_fondo6.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\fondo de batalla(descarga).jpeg")); // NOI18N
        label_fondo6.setText("Terizla");
        jPanel9.add(label_fondo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 650, 310));

        javax.swing.GroupLayout panel_batalla_expLayout = new javax.swing.GroupLayout(panel_batalla_exp.getContentPane());
        panel_batalla_exp.getContentPane().setLayout(panel_batalla_expLayout);
        panel_batalla_expLayout.setHorizontalGroup(
            panel_batalla_expLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_batalla_expLayout.setVerticalGroup(
            panel_batalla_expLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_farmear3.setText("Farmear");
        btn_farmear3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_farmear3MouseClicked(evt);
            }
        });
        jPanel10.add(btn_farmear3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        btn_tienda3.setText("Tienda");
        btn_tienda3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tienda3MouseClicked(evt);
            }
        });
        jPanel10.add(btn_tienda3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        btn_ult3.setText("Ultimate");
        btn_ult3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ult3MouseClicked(evt);
            }
        });
        jPanel10.add(btn_ult3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        btn_ataque3.setText("Atacar");
        btn_ataque3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ataque3MouseClicked(evt);
            }
        });
        jPanel10.add(btn_ataque3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        btn_curar3.setText("Curar");
        btn_curar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_curar3MouseClicked(evt);
            }
        });
        jPanel10.add(btn_curar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 70, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Icono_layla1.png")); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 80, 80));

        txt_vidaenemigo3.setBackground(new java.awt.Color(255, 255, 255));
        txt_vidaenemigo3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_vidaenemigo3.setText("Vida del Enemigo");
        jPanel10.add(txt_vidaenemigo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        txt_oro3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_oro3.setForeground(new java.awt.Color(255, 255, 255));
        txt_oro3.setText("Oro");
        jPanel10.add(txt_oro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 120, 20));

        txt_lvl3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_lvl3.setForeground(new java.awt.Color(255, 255, 255));
        txt_lvl3.setText("Lvl");
        jPanel10.add(txt_lvl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, 20));

        txt_vida3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_vida3.setForeground(new java.awt.Color(255, 255, 255));
        txt_vida3.setText("Vida");
        jPanel10.add(txt_vida3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 110, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\icono_lesley.png")); // NOI18N
        jLabel9.setText("jLabel5");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 90, 60));

        label_fondo7.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\fondo de batalla(descarga).jpeg")); // NOI18N
        label_fondo7.setText("Terizla");
        jPanel10.add(label_fondo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 650, 310));

        javax.swing.GroupLayout panel_batalla_goldLayout = new javax.swing.GroupLayout(panel_batalla_gold.getContentPane());
        panel_batalla_gold.getContentPane().setLayout(panel_batalla_goldLayout);
        panel_batalla_goldLayout.setHorizontalGroup(
            panel_batalla_goldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_batalla_goldLayout.setVerticalGroup(
            panel_batalla_goldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ataquenexo.setText("Atacar");
        btn_ataquenexo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ataquenexoMouseClicked(evt);
            }
        });
        jPanel11.add(btn_ataquenexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        txt_vidanexo.setText("Vida");
        jPanel11.add(txt_vidanexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 160, -1));

        txt_vidajugador.setText("Vida del jugador");
        jPanel11.add(txt_vidajugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 100, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Imagen_nexo.jpg")); // NOI18N
        jPanel11.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 310));

        javax.swing.GroupLayout panel_nexoLayout = new javax.swing.GroupLayout(panel_nexo.getContentPane());
        panel_nexo.getContentPane().setLayout(panel_nexoLayout);
        panel_nexoLayout.setHorizontalGroup(
            panel_nexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_nexoLayout.setVerticalGroup(
            panel_nexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Victory.jpg")); // NOI18N
        jPanel12.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 440));

        javax.swing.GroupLayout VictoryLayout = new javax.swing.GroupLayout(Victory.getContentPane());
        Victory.getContentPane().setLayout(VictoryLayout);
        VictoryLayout.setHorizontalGroup(
            VictoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VictoryLayout.setVerticalGroup(
            VictoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Defeat.jpg")); // NOI18N
        jPanel13.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 460));

        javax.swing.GroupLayout DefeatLayout = new javax.swing.GroupLayout(Defeat.getContentPane());
        Defeat.getContentPane().setLayout(DefeatLayout);
        DefeatLayout.setHorizontalGroup(
            DefeatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DefeatLayout.setVerticalGroup(
            DefeatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setName("Menu"); // NOI18N

        jPanel1.setName("Menu"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_goldlane.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\GoldLane(prueba).png")); // NOI18N
        btn_goldlane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_goldlaneMouseClicked(evt);
            }
        });
        jPanel1.add(btn_goldlane, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 50, 50));

        btn_midlane.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Mid_lane_imagen.png")); // NOI18N
        btn_midlane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_midlaneMouseClicked(evt);
            }
        });
        btn_midlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_midlaneActionPerformed(evt);
            }
        });
        jPanel1.add(btn_midlane, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 50, 50));

        btn_jungler.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Jungler_imagen.png")); // NOI18N
        btn_jungler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_junglerMouseClicked(evt);
            }
        });
        jPanel1.add(btn_jungler, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 50, 40));

        btn_explane.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Exp_lane_imagen.png")); // NOI18N
        btn_explane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_explaneMouseClicked(evt);
            }
        });
        jPanel1.add(btn_explane, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 50, 50));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Bienvenido por favor seleccione una linea");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 240, -1));

        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\OneDrive\\Documentos\\AImagenesProyectoJava\\Odio esto.jpg")); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("Menu");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_midlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_midlaneActionPerformed
        
    }//GEN-LAST:event_btn_midlaneActionPerformed

    private void btn_goldlaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_goldlaneMouseClicked
        //Genera una nueva ventana para que el usuario elija su personaje
        panel_goldlane.setVisible(true);
        panel_goldlane.setModal(true);
        panel_goldlane.pack();
        this.setVisible(false);
    }//GEN-LAST:event_btn_goldlaneMouseClicked

    private void btn_explaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_explaneMouseClicked
        //Genera una nueva ventana para que el usuario elija su personaje
        panel_explane.setVisible(true);
        panel_explane.setModal(true);
        panel_explane.pack();
        this.setVisible(false);
    }//GEN-LAST:event_btn_explaneMouseClicked

    private void btn_lesleyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lesleyActionPerformed
        panel_batalla_gold.setLocationRelativeTo(null);
        Jugador jugador = new Jugador("Lesley", 1000, 0, 1, 15);
        jugadores.add(jugador);
        Enemigo enemigo = new Enemigo("Layla", 1000,0,1,15);
        enemigos.add(enemigo);
        txt_vida3.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
        txt_lvl3.setText(String.valueOf("Lvl " + jugadores.get(0).getNivel()) + "/10");
        txt_oro3.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
        txt_vidaenemigo3.setText(String.valueOf("Vida " + enemigos.get(0).getVida()) + "/1000");
        panel_batalla_gold.setVisible(true);
        panel_batalla_gold.setModal(true);
        panel_batalla_gold.pack();
        panel_goldlane.setVisible(false);
    }//GEN-LAST:event_btn_lesleyActionPerformed

    private void btn_terizlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_terizlaActionPerformed
        /*Al momento de presionar el boton de la seleccion de heroes nos abre una nueva ventana y crea el personaje
        y crea el enemigo y los almacena en un ArrayList separados*/
        panel_batalla_exp.setLocationRelativeTo(null);
        Jugador jugador = new Jugador("Terizla", 1000, 0, 1, 15);
        jugadores.add(jugador);
        Enemigo enemigo = new Enemigo("Yu Zhong", 1000,0,1, 20);
        enemigos.add(enemigo);
        txt_vida2.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
        txt_lvl2.setText(String.valueOf("Lvl " + jugadores.get(0).getNivel()) + "/10");
        txt_oro2.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
        txt_vidaenemigo2.setText(String.valueOf("Vida " + enemigos.get(0).getVida()) + "/1000");
        panel_batalla_exp.setVisible(true);
        panel_batalla_exp.setModal(true);
        panel_batalla_exp.pack();
        panel_explane.setVisible(false);
    }//GEN-LAST:event_btn_terizlaActionPerformed

    private void btn_lesleyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lesleyMouseClicked
  
    }//GEN-LAST:event_btn_lesleyMouseClicked

    private void btn_midlaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_midlaneMouseClicked
        //Genera una nueva ventana para que el usuario elija su personaje
        panel_midlane.setVisible(true);
        panel_midlane.setModal(true);
        panel_midlane.pack();
        this.setVisible(false);
    }//GEN-LAST:event_btn_midlaneMouseClicked

    private void btn_junglerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_junglerMouseClicked
        //Genera una nueva ventana para que el usuario elija su personaje
        panel_jungler.setVisible(true);
        panel_jungler.setModal(true);
        panel_jungler.pack();
        this.setVisible(false);
    }//GEN-LAST:event_btn_junglerMouseClicked

    private void btn_cecilionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cecilionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cecilionActionPerformed

    private void btn_yinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_yinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_yinActionPerformed

    private void btn_cecilionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cecilionMouseClicked
        /*Al momento de presionar el boton de la seleccion de heroes nos abre una nueva ventana y crea el personaje
        y crea el enemigo y los almacena en un ArrayList separados*/
        panel_batalla_jungler.setLocationRelativeTo(null);
        Jugador jugador = new Jugador("Cecilion", 1000, 0, 1, 10);
        jugadores.add(jugador);
        Enemigo enemigo = new Enemigo("Zhask", 1000,0,1,15);
        enemigos.add(enemigo);
        txt_vida1.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
        txt_lvl1.setText(String.valueOf("Lvl " + jugadores.get(0).getNivel()) + "/10");
        txt_oro1.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
        txt_vidaenemigo1.setText(String.valueOf("Vida " + enemigos.get(0).getVida()) + "/1000");
        panel_batalla_mid.setVisible(true);
        panel_batalla_mid.setModal(true);
        panel_batalla_mid.pack();
        panel_midlane.setVisible(false);
    }//GEN-LAST:event_btn_cecilionMouseClicked

    private void btn_yinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yinMouseClicked
        /*Al momento de presionar el boton de la seleccion de heroes nos abre una nueva ventana y crea el personaje
        y crea el enemigo y los almacena en un ArrayList separados*/
        panel_batalla_jungler.setLocationRelativeTo(null);
        Jugador jugador = new Jugador("Yin", 1000, 0, 1, 15);
        jugadores.add(jugador);
        Enemigo enemigo = new Enemigo("Alpha", 1000,0,1,15);
        enemigos.add(enemigo);
        
        txt_vida.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
        txt_lvl.setText(String.valueOf("Lvl " + jugadores.get(0).getNivel()) + "/10");
        txt_oro.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
        txt_vidaenemigo.setText(String.valueOf("Vida " + enemigos.get(0).getVida()) + "/1000");
        panel_batalla_jungler.setVisible(true);
        panel_batalla_jungler.setModal(true);
        panel_batalla_jungler.pack();
        panel_jungler.setVisible(false);
        
        
    }//GEN-LAST:event_btn_yinMouseClicked

    private void btn_curarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_curarMouseClicked
        //Aumenta la vida del jugador
        Curar();
        Bot();
    }//GEN-LAST:event_btn_curarMouseClicked

    private void btn_farmearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_farmearMouseClicked
        //Esta accion genera oro al jugador y al mismo tiempo genera un porcentaje de nivel
        Farmear();
        Bot();
    }//GEN-LAST:event_btn_farmearMouseClicked

    private void btn_ataqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ataqueMouseClicked
        Atacar();
        if (enemigos.get(0).getVida() <= 0) {
            panel_batalla_jungler.setVisible(false);
            txt_vidanexo.setText(String.valueOf(cont) + "/500");
            txt_vidajugador.setText(String.valueOf(jugadores.get(0).getVida()));
            panel_nexo.setVisible(true);
            panel_nexo.setModal(true);
            panel_nexo.pack();
            this.setVisible(false);
        }
        Bot();
        
        
    }//GEN-LAST:event_btn_ataqueMouseClicked

    private void btn_tiendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tiendaMouseClicked
        panel_tienda.setVisible(true);
        panel_tienda.setModal(true);
        panel_tienda.pack();
    }//GEN-LAST:event_btn_tiendaMouseClicked

    private void btn_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regresarMouseClicked

        panel_tienda.setVisible(false);
    }//GEN-LAST:event_btn_regresarMouseClicked

    private void btn_garrasdehaasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_garrasdehaasMouseClicked
        if (jugadores.get(0).getOro() < 1810) {
            JOptionPane.showMessageDialog(this, "Lo sentimos no tienes suficiente dinero");
            panel_tienda.setVisible(false);
        }else{
            jugadores.get(0).setDano(jugadores.get(0).getDano() + 70);
            jugadores.get(0).setOro(jugadores.get(0).getOro() - 1810);
            JOptionPane.showMessageDialog(this, "Su ataque ha aumentado, Vuelva pronto");
            panel_tienda.setVisible(false);
            txt_oro.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
            txt_oro1.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
            txt_oro2.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
            txt_oro3.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
            
        }
        Bot();
    }//GEN-LAST:event_btn_garrasdehaasMouseClicked

    private void btn_filodesesperanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_filodesesperanteMouseClicked
        if (jugadores.get(0).getOro() < 3010) {
            JOptionPane.showMessageDialog(this, "Lo sentimos no tienes suficiente dinero");
            panel_tienda.setVisible(false);
        }else{
            jugadores.get(0).setDano(jugadores.get(0).getDano() + 100);
            jugadores.get(0).setOro(jugadores.get(0).getOro() - 3010);
            JOptionPane.showMessageDialog(this, "Su ataque ha aumentado, Vuelva pronto");
            panel_tienda.setVisible(false);
            txt_oro.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
            txt_oro1.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
            txt_oro2.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
            txt_oro3.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
            
        }
        Bot();
    }//GEN-LAST:event_btn_filodesesperanteMouseClicked

    private void btn_varitadegenioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_varitadegenioMouseClicked
        if (jugadores.get(0).getOro() < 2000) {
            JOptionPane.showMessageDialog(this, "Lo sentimos no tienes suficiente dinero");
            panel_tienda.setVisible(false);
        }else{
            jugadores.get(0).setDano(jugadores.get(0).getDano() + 60);
            jugadores.get(0).setOro(jugadores.get(0).getOro() - 2000);
            jugadores.get(0).setVida(jugadores.get(0).getVida() + 100);
            JOptionPane.showMessageDialog(this, "Su ataque ha aumentado, Vuelva pronto");
            panel_tienda.setVisible(false);
            txt_oro.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
            txt_oro1.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
            txt_oro2.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
            txt_oro3.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
            txt_vida.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
            txt_vida1.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
            txt_vida2.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
            txt_vida3.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
            
        }
        Bot();
    }//GEN-LAST:event_btn_varitadegenioMouseClicked

    private void btn_alassangrientasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_alassangrientasMouseClicked
        if (jugadores.get(0).getOro() < 3010) {
            JOptionPane.showMessageDialog(this, "Lo sentimos no tienes suficiente dinero");
            panel_tienda.setVisible(false);
        }else{
            jugadores.get(0).setDano(jugadores.get(0).getDano() + 90);
            jugadores.get(0).setOro(jugadores.get(0).getOro() - 3000);
            jugadores.get(0).setVida(jugadores.get(0).getVida() + 200);
            JOptionPane.showMessageDialog(this, "Su ataque ha aumentado, Vuelva pronto");
            panel_tienda.setVisible(false);
            txt_oro.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
            txt_vida.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
            txt_oro1.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
            txt_oro2.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
            txt_oro3.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
            txt_vida.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
            txt_vida1.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
            txt_vida2.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
            txt_vida3.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
        }
        Bot();
    }//GEN-LAST:event_btn_alassangrientasMouseClicked

    private void btn_ultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ultMouseClicked
        ult();
        if (enemigos.get(0).getVida() <= 0) {
            panel_batalla_jungler.setVisible(false);
            txt_vidanexo.setText(String.valueOf(cont) + "/500");
            txt_vidajugador.setText(String.valueOf(jugadores.get(0).getVida()));
            panel_nexo.setVisible(true);
            panel_nexo.setModal(true);
            panel_nexo.pack();
            this.setVisible(false);
        }
        Bot();
    }//GEN-LAST:event_btn_ultMouseClicked

    private void btn_farmear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_farmear1MouseClicked
        Farmear();
        Bot();
    }//GEN-LAST:event_btn_farmear1MouseClicked

    private void btn_tienda1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tienda1MouseClicked
        panel_tienda.setVisible(true);
        panel_tienda.setModal(true);
        panel_tienda.pack();
    }//GEN-LAST:event_btn_tienda1MouseClicked

    private void btn_ult1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ult1MouseClicked
        ult();
        if (enemigos.get(0).getVida() <= 0) {
            panel_batalla_mid.setVisible(false);
            txt_vidanexo.setText(String.valueOf(cont) + "/500");
            panel_nexo.setVisible(true);
            panel_nexo.setModal(true);
            panel_nexo.pack();
            this.setVisible(false);
        }
        Bot();
    }//GEN-LAST:event_btn_ult1MouseClicked

    private void btn_ataque1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ataque1MouseClicked
        Atacar();
        if (enemigos.get(0).getVida() <= 0) {
            panel_batalla_mid.setVisible(false);
            txt_vidanexo.setText(String.valueOf(cont) + "/500");
            txt_vidajugador.setText(String.valueOf(jugadores.get(0).getVida()));
            panel_nexo.setVisible(true);
            panel_nexo.setModal(true);
            panel_nexo.pack();
            this.setVisible(false);
        }
        Bot();
    }//GEN-LAST:event_btn_ataque1MouseClicked

    private void btn_curar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_curar1MouseClicked
        Curar();
        Bot();
    }//GEN-LAST:event_btn_curar1MouseClicked

    private void btn_farmear2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_farmear2MouseClicked
        Farmear();
        Bot();
    }//GEN-LAST:event_btn_farmear2MouseClicked

    private void btn_tienda2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tienda2MouseClicked
        panel_tienda.setVisible(true);
        panel_tienda.setModal(true);
        panel_tienda.pack();
    }//GEN-LAST:event_btn_tienda2MouseClicked

    private void btn_ult2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ult2MouseClicked
        ult();
        if (enemigos.get(0).getVida() <= 0) {
            panel_batalla_exp.setVisible(false);
            txt_vidanexo.setText(String.valueOf(cont) + "/500");
            txt_vidajugador.setText(String.valueOf(jugadores.get(0).getVida()));
            panel_nexo.setVisible(true);
            panel_nexo.setModal(true);
            panel_nexo.pack();
            this.setVisible(false);
        }
        Bot();
    }//GEN-LAST:event_btn_ult2MouseClicked

    private void btn_ataque2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ataque2MouseClicked
        Atacar();
        if (enemigos.get(0).getVida() <= 0) {
            panel_batalla_exp.setVisible(false);
            txt_vidanexo.setText(String.valueOf(cont) + "/500");
            txt_vidajugador.setText(String.valueOf(jugadores.get(0).getVida()));
            panel_nexo.setVisible(true);
            panel_nexo.setModal(true);
            panel_nexo.pack();
            this.setVisible(false);
        }
        Bot();
    }//GEN-LAST:event_btn_ataque2MouseClicked

    private void btn_curar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_curar2MouseClicked
        Curar();
        Bot();
    }//GEN-LAST:event_btn_curar2MouseClicked

    private void btn_farmear3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_farmear3MouseClicked
        Farmear();
        Bot();
    }//GEN-LAST:event_btn_farmear3MouseClicked

    private void btn_tienda3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tienda3MouseClicked
        panel_tienda.setVisible(true);
        panel_tienda.setModal(true);
        panel_tienda.pack();
    }//GEN-LAST:event_btn_tienda3MouseClicked

    private void btn_ult3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ult3MouseClicked
        ult();
        if (enemigos.get(0).getVida() <= 0) {
            panel_batalla_gold.setVisible(false);
            txt_vidanexo.setText(String.valueOf(cont) + "/500");
            txt_vidajugador.setText(String.valueOf(jugadores.get(0).getVida()));
            panel_nexo.setVisible(true);
            panel_nexo.setModal(true);
            panel_nexo.pack();
            this.setVisible(false);
        }
        Bot();
    }//GEN-LAST:event_btn_ult3MouseClicked

    private void btn_ataque3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ataque3MouseClicked
        Atacar();
        if (enemigos.get(0).getVida() <= 0) {
            panel_batalla_gold.setVisible(false);
            txt_vidanexo.setText(String.valueOf(cont) + "/500");
            txt_vidajugador.setText(String.valueOf(jugadores.get(0).getVida()));
            panel_nexo.setVisible(true);
            panel_nexo.setModal(true);
            panel_nexo.pack();
            this.setVisible(false);
        }
        Bot();
    }//GEN-LAST:event_btn_ataque3MouseClicked

    private void btn_curar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_curar3MouseClicked
        Curar();
        Bot();
    }//GEN-LAST:event_btn_curar3MouseClicked

    private void btn_ataquenexoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ataquenexoMouseClicked
        if (cont <= 0) {
            Victory.setVisible(true);
            Victory.setModal(true);
            Victory.pack();
            panel_nexo.setVisible(false);
        }else if(jugadores.get(0).getVida() <= 0){
            JOptionPane.showMessageDialog(this, "Has perdido");
            Defeat.setVisible(true);
            Defeat.setModal(true);
            Defeat.pack();
            panel_nexo.setVisible(false);
        }
        else{
            cont = cont - jugadores.get(0).getDano();
            txt_vidanexo.setText(String.valueOf(cont) + "/500"); 
            jugadores.get(0).setVida(jugadores.get(0).getVida() - ataquenexo(cont_nexo));
            txt_vidajugador.setText(String.valueOf(jugadores.get(0).getVida()));
            cont_nexo += 2;
        }
   
        
    }//GEN-LAST:event_btn_ataquenexoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daniel_Deras_Proyecto1_1241.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daniel_Deras_Proyecto1_1241.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daniel_Deras_Proyecto1_1241.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daniel_Deras_Proyecto1_1241.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daniel_Deras_Proyecto1_1241().setVisible(true);
            }
        });
    }
    //metodo de Inteligencia Artificial
    //Por cada turno que tenga el jugador tambien el bot va actuar dependiendo de un random
    public void Bot(){
        int random = numr.nextInt(1,4);
        //Atacar
        if (random == 1) {
            jugadores.get(0).setVida( jugadores.get(0).getVida() - enemigos.get(0).getDano());
            JOptionPane.showMessageDialog(this, "El enemigo te ha golpeado");
            txt_vida.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
            txt_vida1.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
            txt_vida2.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
            txt_vida3.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
            
            if (jugadores.get(0).getVida() <= 0) {
                JOptionPane.showMessageDialog(this, "Has perdido");
                panel_batalla_jungler.setVisible(false);
                panel_batalla_mid.setVisible(false);
                panel_batalla_exp.setVisible(false);
                panel_batalla_gold.setVisible(false);
            }
            
        }//Farmear
        else if (random == 2) {
            enemigos.get(0).setOro(enemigos.get(0).getOro() + 500);
              
        }//Comprar
        else if (random == 3) {
            if (enemigos.get(0).getOro()  >= 1000) {
                JOptionPane.showMessageDialog(this, "Cuidado que el enemigo ha comprado un objeto");
                enemigos.get(0).setDano(enemigos.get(0).getDano() + 50);
            }
        }
    
    }
    //Metodos 
    
    //Metodo para validar suber de nivel
    public void SubirLvl(){
        switch (cont_oro){
                case 2:
                    jugadores.get(0).setNivel(2);
                    break;
                case 4:
                    jugadores.get(0).setNivel(3);
                    break;
                case 6:
                    jugadores.get(0).setNivel(4);
                    break;
                case 8:
                    jugadores.get(0).setNivel(5);
                    break;
                case 10:
                    jugadores.get(0).setNivel(6);
                    break;
                case 12:
                    jugadores.get(0).setNivel(7);
                    break;
                case 14:
                    jugadores.get(0).setNivel(8);
                    break;
                case 16:
                    jugadores.get(0).setNivel(9);
                    break;
                case 18:
                    jugadores.get(0).setNivel(10);
                    break;
            }
    }
    //Metodo para curar
    public  void Curar(){
        if (jugadores.get(0).getVida()<1000 && cont_vida > 0) {
            jugadores.get(0).setVida(jugadores.get(0).getVida() + 250);
            JOptionPane.showMessageDialog(this, "Te has curado: " + 200 + "hp");
            txt_vida.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
            txt_vida1.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
            txt_vida2.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
            txt_vida3.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
            cont_vida--;
        }
        if (cont_vida <= 0) {
            JOptionPane.showMessageDialog(this, "Se te acabaron las curas");
        }
        if (jugadores.get(0).getVida()>999) {
            jugadores.get(0).setVida(1000);
            txt_vida.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
            txt_vida1.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
            txt_vida2.setText(String.valueOf("Vida " + jugadores.get(0).getVida()) + "/1000");
        }
    }
    //Metodo para farmear
    public void Farmear(){
        jugadores.get(0).setOro(jugadores.get(0).getOro() + 250);
        txt_oro.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
        txt_oro1.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
        txt_oro2.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
        txt_oro3.setText(String.valueOf("Oro " + jugadores.get(0).getOro()));
        
        cont_oro ++;
        SubirLvl();
        JOptionPane.showMessageDialog(this, "Has farmeado " + 250 + " Oro");
        txt_lvl.setText(String.valueOf("Lvl " + jugadores.get(0).getNivel()) + "/10");
        txt_lvl1.setText(String.valueOf("Lvl " + jugadores.get(0).getNivel()) + "/10");
        txt_lvl2.setText(String.valueOf("Lvl " + jugadores.get(0).getNivel()) + "/10");
        txt_lvl3.setText(String.valueOf("Lvl " + jugadores.get(0).getNivel()) + "/10");
        
    }
    
    //Metodo de Ataque
    public void Atacar(){
        enemigos.get(0).setVida(enemigos.get(0).getVida() - jugadores.get(0).getDano());
        txt_vidaenemigo.setText(String.valueOf("Vida " + enemigos.get(0).getVida()) + "/1000");
        txt_vidaenemigo1.setText(String.valueOf("Vida " +enemigos.get(0).getVida()) + "/1000");
        txt_vidaenemigo2.setText(String.valueOf("Vida " +enemigos.get(0).getVida()) + "/1000");
        txt_vidaenemigo3.setText(String.valueOf("Vida " +enemigos.get(0).getVida()) + "/1000");
        JOptionPane.showMessageDialog(this, "Le hiciste: " + jugadores.get(0).getDano());
        if (enemigos.get(0).getVida() <= 0) {
            JOptionPane.showMessageDialog(this, "Enhorabuena, has derrotado al campeon :) ");
        }
    }
    //Metodo de ult
    public void ult(){
        if (cont_ult < 1) {
            JOptionPane.showMessageDialog(this, "Ya has utilizado tu ultimate");
        }else if(jugadores.get(0).getNivel() < 4){
            JOptionPane.showMessageDialog(this, "No tienes el nivel suficiente, debes ser lvl 4");
            
        }else{
            enemigos.get(0).setVida(enemigos.get(0).getVida() - (jugadores.get(0).getDano() + (jugadores.get(0).getDano()/3)));
            txt_vidaenemigo.setText(String.valueOf("Vida" +enemigos.get(0).getVida()) + "/1000");
            txt_vidaenemigo1.setText(String.valueOf("Vida" +enemigos.get(0).getVida()) + "/1000");
            txt_vidaenemigo2.setText(String.valueOf("Vida" +enemigos.get(0).getVida()) + "/1000");
            txt_vidaenemigo3.setText(String.valueOf("Vida" +enemigos.get(0).getVida()) + "/1000");

            cont_ult--;
        }if (enemigos.get(0).getVida() <= 0) {
            JOptionPane.showMessageDialog(this, "Enhorabuena, has derrotado al campeon :) ");
        }
    }
    
    //Metodo de ataque del nexo
    public static int ataquenexo(int x){
        if (x == 0) {
            return 0;
        }
 
    return x + (ataquenexo(x-1));
    }

    //Variables globales
    ArrayList<Jugador> jugadores = new ArrayList();
    ArrayList<Enemigo> enemigos = new ArrayList();
    int cont_vida = 3;
    int cont = 500;
    int cont_nexo = 1;
    int cont_oro = 0;
    int cont_ult = 1;
    Random numr = new Random();
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Defeat;
    private javax.swing.JDialog Victory;
    private javax.swing.JButton btn_alassangrientas;
    private javax.swing.JButton btn_ataque;
    private javax.swing.JButton btn_ataque1;
    private javax.swing.JButton btn_ataque2;
    private javax.swing.JButton btn_ataque3;
    private javax.swing.JButton btn_ataquenexo;
    private javax.swing.JButton btn_cecilion;
    private javax.swing.JButton btn_curar;
    private javax.swing.JButton btn_curar1;
    private javax.swing.JButton btn_curar2;
    private javax.swing.JButton btn_curar3;
    private javax.swing.JButton btn_explane;
    private javax.swing.JButton btn_farmear;
    private javax.swing.JButton btn_farmear1;
    private javax.swing.JButton btn_farmear2;
    private javax.swing.JButton btn_farmear3;
    private javax.swing.JButton btn_filodesesperante;
    private javax.swing.JButton btn_garrasdehaas;
    private javax.swing.JButton btn_goldlane;
    private javax.swing.JButton btn_jungler;
    private javax.swing.JButton btn_lesley;
    private javax.swing.JButton btn_midlane;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JButton btn_terizla;
    private javax.swing.JButton btn_tienda;
    private javax.swing.JButton btn_tienda1;
    private javax.swing.JButton btn_tienda2;
    private javax.swing.JButton btn_tienda3;
    private javax.swing.JButton btn_ult;
    private javax.swing.JButton btn_ult1;
    private javax.swing.JButton btn_ult2;
    private javax.swing.JButton btn_ult3;
    private javax.swing.JButton btn_varitadegenio;
    private javax.swing.JButton btn_yin;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel label_fondo;
    private javax.swing.JLabel label_fondo1;
    private javax.swing.JLabel label_fondo2;
    private javax.swing.JLabel label_fondo3;
    private javax.swing.JLabel label_fondo4;
    private javax.swing.JLabel label_fondo5;
    private javax.swing.JLabel label_fondo6;
    private javax.swing.JLabel label_fondo7;
    private javax.swing.JDialog panel_batalla_exp;
    private javax.swing.JDialog panel_batalla_gold;
    private javax.swing.JDialog panel_batalla_jungler;
    private javax.swing.JDialog panel_batalla_mid;
    private javax.swing.JDialog panel_explane;
    private javax.swing.JDialog panel_goldlane;
    private javax.swing.JDialog panel_jungler;
    private javax.swing.JDialog panel_midlane;
    private javax.swing.JDialog panel_nexo;
    private javax.swing.JDialog panel_tienda;
    private javax.swing.JLabel txt_lvl;
    private javax.swing.JLabel txt_lvl1;
    private javax.swing.JLabel txt_lvl2;
    private javax.swing.JLabel txt_lvl3;
    private javax.swing.JLabel txt_oro;
    private javax.swing.JLabel txt_oro1;
    private javax.swing.JLabel txt_oro2;
    private javax.swing.JLabel txt_oro3;
    private javax.swing.JLabel txt_vida;
    private javax.swing.JLabel txt_vida1;
    private javax.swing.JLabel txt_vida2;
    private javax.swing.JLabel txt_vida3;
    private javax.swing.JLabel txt_vidaenemigo;
    private javax.swing.JLabel txt_vidaenemigo1;
    private javax.swing.JLabel txt_vidaenemigo2;
    private javax.swing.JLabel txt_vidaenemigo3;
    private javax.swing.JLabel txt_vidajugador;
    private javax.swing.JLabel txt_vidanexo;
    // End of variables declaration//GEN-END:variables
}
